#!/bin/bash
# auto_optimizer.sh
# Automatische System-Optimierung

set -e

WORKSPACE="/root/.openclaw/workspace"
AURELPRO="$WORKSPACE/AURELPRO"
SKILLS_DIR="$WORKSPACE/skills"
LOGS_DIR="$AURELPRO/logs"
OPTIMIZATION_DIR="$AURELPRO/optimization"
DATE=$(date +%Y-%m-%d)
TIMESTAMP=$(date +%Y%m%d_%H%M%S)

# Ensure directories exist
mkdir -p "$OPTIMIZATION_DIR"
mkdir -p "$OPTIMIZATION_DIR/reports"

echo "⚡ Auto Optimizer v1.0"
echo "====================="
echo "Datum: $DATE"
echo ""

# Initialize optimization log
OPT_LOG="$OPTIMIZATION_DIR/optimization_${DATE}.log"
echo "[$TIMESTAMP] Auto Optimizer gestartet" > "$OPT_LOG"

declare -i OPTIMIZATIONS_MADE=0

# ============================================
# OPTIMIERUNG 1: Log-Rotation
# ============================================
echo "📊 Prüfe Log-Größen..."

ORCHESTRATOR_LOGS="$AURELPRO/orchestrator_logs"
if [ -d "$ORCHESTRATOR_LOGS" ]; then
    LOG_SIZE=$(du -sm "$ORCHESTRATOR_LOGS" 2>/dev/null | cut -f1 || echo "0")
    echo "  Orchestrator Logs: ${LOG_SIZE}MB"
    
    if [ "$LOG_SIZE" -gt 10 ]; then
        echo "  ⚠️  Logs zu groß - Rotation empfohlen"
        echo "[$TIMESTAMP] WARN: Orchestrator Logs ${LOG_SIZE}MB > 10MB" >> "$OPT_LOG"
        
        # Create archive directory
        ARCHIVE_DIR="$AURELPRO/archive/logs_${DATE}"
        mkdir -p "$ARCHIVE_DIR"
        
        # Move old logs (>7 Tage)
        find "$ORCHESTRATOR_LOGS" -name "*.log" -type f -mtime +7 -exec mv {} "$ARCHIVE_DIR/" \; 2>/dev/null || true
        
        # Compress archived logs
        if [ -f "$ARCHIVE_DIR"/*.log 2>/dev/null ]; then
            tar -czf "${ARCHIVE_DIR}.tar.gz" -C "$ARCHIVE_DIR" . 2>/dev/null || true
            rm -rf "$ARCHIVE_DIR"
            echo "  ✅ Alte Logs archiviert: ${ARCHIVE_DIR}.tar.gz"
            echo "[$TIMESTAMP] OPTIMIZED: Log rotation executed" >> "$OPT_LOG"
            OPTIMIZATIONS_MADE=$((OPTIMIZATIONS_MADE + 1))
        fi
    else
        echo "  ✅ Logs OK"
    fi
fi

echo ""

# ============================================
# OPTIMIERUNG 2: Skill-Dokumentation
# ============================================
echo "📚 Prüfe Skill-Dokumentation..."

SKILLS_WITHOUT_README=()
SKILLS_WITHOUT_SKILL_MD=()

for skill_dir in "$SKILLS_DIR"/*/; do
    if [ -d "$skill_dir" ]; then
        skill_name=$(basename "$skill_dir")
        
        # Check for README.md
        if [ ! -f "$skill_dir/README.md" ]; then
            SKILLS_WITHOUT_README+=("$skill_name")
        fi
        
        # Check for SKILL.md
        if [ ! -f "$skill_dir/SKILL.md" ]; then
            SKILLS_WITHOUT_SKILL_MD+=("$skill_name")
        fi
    fi
done

echo "  Skills ohne README: ${#SKILLS_WITHOUT_README[@]}"
echo "  Skills ohne SKILL.md: ${#SKILLS_WITHOUT_SKILL_MD[@]}"

if [ ${#SKILLS_WITHOUT_README[@]} -gt 0 ]; then
    echo "  ⚠️  Dokumentations-Lücken erkannt"
    echo "[$TIMESTAMP] WARN: ${#SKILLS_WITHOUT_README[@]} skills missing README" >> "$OPT_LOG"
fi

# Generate missing READMEs for simple skills
for skill_name in "${SKILLS_WITHOUT_README[@]}"; do
    skill_dir="$SKILLS_DIR/$skill_name"
    
    # Only auto-generate if there's a main script
    if [ -f "$skill_dir/$skill_name.sh" ] || [ -f "$skill_dir/run.sh" ]; then
        cat > "$skill_dir/README.md" << EOF
# $skill_name

## Zweck
Automatisch generierte README für $skill_name.

## Nutzung
\`\`\`bash
bash $skill_name.sh
\`\`\`

## Dateien
- Hauptskript im Verzeichnis
- SKILL.md für Details

---
Auto-generated by auto_optimizer on $DATE
EOF
        echo "  ✅ README erstellt: $skill_name"
        echo "[$TIMESTAMP] OPTIMIZED: Created README for $skill_name" >> "$OPT_LOG"
        OPTIMIZATIONS_MADE=$((OPTIMIZATIONS_MADE + 1))
    fi
done

echo ""

# ============================================
# OPTIMIERUNG 3: Temp-Datei-Bereinigung
# ============================================
echo "🧹 Prüfe temporäre Dateien..."

TEMP_FILES=0
TEMP_SIZE=0

# Find temp files in workspace
while IFS= read -r file; do
    TEMP_FILES=$((TEMP_FILES + 1))
    SIZE=$(stat -f%z "$file" 2>/dev/null || stat -c%s "$file" 2>/dev/null || echo "0")
    TEMP_SIZE=$((TEMP_SIZE + SIZE))
done < <(find "$WORKSPACE" -name "*.tmp" -o -name "*.temp" -o -name "*~" 2>/dev/null | head -50)

if [ "$TEMP_FILES" -gt 0 ]; then
    echo "  Gefunden: $TEMP_FILES temporäre Dateien ($(numfmt --to=iec $TEMP_SIZE 2>/dev/null || echo "${TEMP_SIZE}B"))"
    
    # Remove temp files older than 1 day
    find "$WORKSPACE" -name "*.tmp" -o -name "*.temp" -o -name "*~" -mtime +1 -delete 2>/dev/null || true
    echo "  ✅ Alte temporäre Dateien bereinigt"
    echo "[$TIMESTAMP] OPTIMIZED: Cleaned $TEMP_FILES temp files" >> "$OPT_LOG"
    OPTIMIZATIONS_MADE=$((OPTIMIZATIONS_MADE + 1))
else
    echo "  ✅ Keine temporären Dateien"
fi

echo ""

# ============================================
# OPTIMIERUNG 4: Memory-Index-Update
# ============================================
echo "📇 Prüfe Memory-Index..."

MEMORY_DIR="$WORKSPACE/memory"
INDEX_FILE="$MEMORY_DIR/INDEX.md"

if [ -d "$MEMORY_DIR" ]; then
    MEMORY_COUNT=$(find "$MEMORY_DIR" -name "*.md" -type f | wc -l)
    echo "  Memory-Dateien: $MEMORY_COUNT"
    
    # Check if index needs update (if older than 1 day)
    if [ -f "$INDEX_FILE" ]; then
        INDEX_AGE=$(( ($(date +%s) - $(stat -c%Y "$INDEX_FILE" 2>/dev/null || stat -f%m "$INDEX_FILE")) / 86400 ))
        if [ "$INDEX_AGE" -gt 1 ]; then
            echo "  ⚠️  Index veraltet ($INDEX_AGE Tage)"
            
            # Update index
            cat > "$INDEX_FILE" << EOF
# Memory Index

**Letzte Aktualisierung:** $(date '+%Y-%m-%d %H:%M:%S')

## Memory-Dateien ($MEMORY_COUNT)

EOF
            find "$MEMORY_DIR" -name "*.md" -type f | sort | while read -r f; do
                name=$(basename "$f")
                size=$(du -h "$f" | cut -f1)
                echo "- $name ($size)" >> "$INDEX_FILE"
            done
            
            echo "  ✅ Index aktualisiert"
            echo "[$TIMESTAMP] OPTIMIZED: Updated memory index" >> "$OPT_LOG"
            OPTIMIZATIONS_MADE=$((OPTIMIZATIONS_MADE + 1))
        else
            echo "  ✅ Index aktuell"
        fi
    fi
fi

echo ""

# ============================================
# OPTIMIERUNG 5: AURELPRO System-Status
# ============================================
echo "⚙️  Prüfe AURELPRO System-Status..."

SYSTEM_STATE="$AURELPRO/active/system_state.json"
if [ -f "$SYSTEM_STATE" ]; then
    # Check if state is older than 1 day
    STATE_AGE=$(( ($(date +%s) - $(stat -c%Y "$SYSTEM_STATE" 2>/dev/null || stat -f%m "$SYSTEM_STATE")) / 86400 ))
    
    if [ "$STATE_AGE" -gt 0 ]; then
        echo "  ⚠️  System-State veraltet ($STATE_AGE Tage)"
        echo "[$TIMESTAMP] WARN: System state outdated" >> "$OPT_LOG"
    else
        echo "  ✅ System-State aktuell"
    fi
fi

echo ""

# ============================================
# ZUSAMMENFASSUNG
# ============================================
echo "📋 Optimierungs-Zusammenfassung"
echo "==============================="
echo ""
echo "Durchgeführte Optimierungen: $OPTIMIZATIONS_MADE"
echo ""

if [ $OPTIMIZATIONS_MADE -gt 0 ]; then
    echo "✅ System wurde optimiert!"
    echo "   Details: $OPT_LOG"
else
    echo "✅ System ist bereits optimal"
fi

echo ""
echo "[$TIMESTAMP] Auto Optimizer beendet - $OPTIMIZATIONS_MADE Optimierungen" >> "$OPT_LOG"

# Create optimization report
REPORT_FILE="$OPTIMIZATION_DIR/reports/optimization_report_${DATE}.md"

cat > "$REPORT_FILE" << EOF
# Optimization Report - $DATE

**Generiert:** $(date '+%Y-%m-%d %H:%M:%S') CST  
**Optimierungen:** $OPTIMIZATIONS_MADE

---

## Durchgeführte Optimierungen

EOF

if [ $OPTIMIZATIONS_MADE -gt 0 ]; then
    echo "Siehe Log: $OPT_LOG" >> "$REPORT_FILE"
else
    echo "Keine Optimierungen nötig - System ist optimal." >> "$REPORT_FILE"
fi

cat >> "$REPORT_FILE" << EOF

---

## System-Status

- **Log-Größe:** $(du -sm "$AURELPRO/orchestrator_logs" 2>/dev/null | cut -f1 || echo "0")MB
- **Memory-Dateien:** $(find "$WORKSPACE/memory" -name "*.md" 2>/dev/null | wc -l)
- **Skills:** $(find "$SKILLS_DIR" -maxdepth 1 -type d 2>/dev/null | wc -l)

---

⚡ Optimized with 🗡️💚🔍
EOF

echo "📄 Report erstellt: $REPORT_FILE"
echo ""
echo "🎉 Auto Optimierung abgeschlossen!"
