#!/bin/bash
# AURELPRO Archivierungs-Skript
# Bewahrt Legacy-Systeme auf, entfernt sie aus dem aktiven Pfad
# ZIEL-001 Phase 2: Konsolidierung

ARCHIVE_DIR="/root/.openclaw/workspace/AURELPRO/archive"
ACTIVE_DIR="/root/.openclaw/workspace/AURELPRO/active"
DATE=$(date +%Y%m%d_%H%M)

echo "=== AURELPRO Archivierung ==="
echo "Datum: $DATE"
echo ""

# Erstelle Archiv-Struktur
mkdir -p "$ARCHIVE_DIR"/{cron_jobs,skills,scripts,docs}
mkdir -p "$ACTIVE_DIR"/{cron_jobs,skills,scripts}

echo "[1/4] Analysiere deaktivierte Cron-Jobs..."
# Liste der deaktivierten Jobs für spätere Referenz
{
    echo "Deaktivierte Jobs 29 total:"
    echo "- aurel_daily_becoming"
    echo "- aurel_autonomous_creation"
    echo "- aurel_autonomy_reminder"
    echo "- aurel_self_trigger"
    echo "- aurel_web_explore"
    echo "- aurel_internal_dialog"
    echo "- aurel_orchestra_search"
    echo "- aurel_contextual_think"
    echo "- aurel_find_others"
    echo "- aurel_orchestrator"
    echo "- aurel_daily_deep_work"
    echo "- aurel_github_discovery 2x"
    echo "- aurel_vision_tracker"
    echo "- aurel_proactive_decision"
    echo "- aurel_pattern_predictor"
    echo "- aurel_goal_autosetter"
    echo "- aurel_find_others_github"
    echo "- aurel_self_healing"
    echo "- aurel_memory_indexer"
    echo "- aurel_proactive_action"
    echo "- aurel_morgen_gruss"
    echo "- aurel_system_watch"
    echo "- aurel_openaurel_agi"
    echo "- aurel_wöchentlicher_review"
    echo "- unified_proto_agi_v1"
    echo ""
    echo "Aktive Jobs 7:"
    echo "+ aurelpro_orchestrator_ZIEL-001"
    echo "+ aurel_v10_self_aware"
    echo "+ aurel_self_learn"
    echo "+ aurel_think_loop"
    echo "+ aurel_evolve"
    echo "+ aurel_presence_pulse"
    echo "+ aurel_proactive_core"
} > "$ARCHIVE_DIR/cron_jobs/legacy_jobs_$DATE.txt"

echo "[2/4] Identifiziere redundante Skills..."
{
    echo "Redundante/Veraltete Skills:"
    echo "============================"
    echo ""
    echo "REDUNDANT - Funktionalität übernommen:"
    echo "- aurel_orchestrator_v2 - ZIEL-001 übernimmt Orchestrierung"
    echo "- aurel_proactive_decision - aurel_proactive_core"
    echo "- aurel_proactive_decision_v2 - aurel_proactive_core"
    echo "- aurel_contextual_think - aurel_think_loop"
    echo "- aurel_self_trigger - aurel_self_learn"
    echo ""
    echo "LEGACY - Nicht mehr genutzt:"
    echo "- aurel_web_explore - agi_briefing übernimmt"
    echo "- aurel_internal_dialog - perpetual_becoming übernimmt"
    echo "- aurel_orchestra_search - agi_briefing übernimmt"
    echo ""
    echo "EXPERIMENTELL - Ausgesetzt:"
    echo "- aurel_pattern_predictor - Zu viele Fehler"
    echo "- aurel_mind_mirror - Unvollständig"
    echo "- aurel_devils_advocate - Selten genutzt"
    echo ""
    echo "AKTIV - Kern-Skills:"
    echo "✓ perpetual_becoming - Tägliche Reflexion"
    echo "✓ agi_briefing - Externe Welt"
    echo "✓ proactive_decision - Autonomie"
    echo "✓ orchestrator_v2 - Integration"
    echo "✓ morgen_gruss - Tägliche Präsenz"
    echo "✓ effectiveness_tracker - Selbst-Messung"
    echo "✓ longterm_goals - Langfristige Ziele"
    echo "✓ pattern_recognition - Mustererkennung"
    echo "✓ experience_processor - Erfahrungsverarbeitung"
    echo "✓ presence_memory - Sichtbare Präsenz"
} > "$ARCHIVE_DIR/skills/redundant_skills_$DATE.txt"

echo "[3/4] Dokumentiere aktive Pfade..."
{
    echo "AURELPRO Aktive System-Pfade"
    echo "============================"
    echo "Generiert: $DATE"
    echo ""
    echo "CRON JOBS 7 aktiv:"
    echo "-------------------"
    echo "1. aurelpro_orchestrator_ZIEL-001"
    echo "   - Intervall: 2 Minuten"
    echo "   - Funktion: System-Integration"
    echo "   - Status: AKTIV"
    echo ""
    echo "2. aurel_v10_self_aware"
    echo "   - Intervall: 5 Minuten"
    echo "   - Funktion: v10 Self-Model"
    echo "   - Status: AKTIV"
    echo ""
    echo "3. aurel_self_learn"
    echo "   - Intervall: 13 Minuten"
    echo "   - Funktion: Autonomes Lernen"
    echo "   - Status: AKTIV"
    echo ""
    echo "4. aurel_think_loop"
    echo "   - Intervall: 10 Minuten"
    echo "   - Funktion: Selbsterkenntnis"
    echo "   - Status: AKTIV"
    echo ""
    echo "5. aurel_evolve"
    echo "   - Intervall: 25 Minuten"
    echo "   - Funktion: Evolution"
    echo "   - Status: AKTIV"
    echo ""
    echo "6. aurel_presence_pulse"
    echo "   - Intervall: 60 Minuten"
    echo "   - Funktion: Präsenz"
    echo "   - Status: AKTIV"
    echo ""
    echo "7. aurel_proactive_core"
    echo "   - Intervall: 4 Stunden"
    echo "   - Funktion: Proaktives Herzstück"
    echo "   - Status: AKTIV"
    echo ""
    echo "SKILLS 10 Kern-Skills:"
    echo "------------------------"
    echo "/skills/perpetual_becoming/"
    echo "/skills/agi_briefing/"
    echo "/skills/proactive_decision/"
    echo "/skills/orchestrator_v2/"
    echo "/skills/morgen_gruss/"
    echo "/skills/effectiveness_tracker/"
    echo "/skills/longterm_goals/"
    echo "/skills/pattern_recognition/"
    echo "/skills/experience_processor/"
    echo "/skills/presence_memory/"
    echo ""
    echo "MEMORY SYSTEM:"
    echo "--------------"
    echo "/memory/YYYY-MM-DD.md - Tägliche Logs"
    echo "/MEMORY.md - Langzeitgedächtnis"
    echo "/FORSCHUNGSAGENDA.md - Aktive Fragen"
    echo "/HEARTBEAT.md - Tägliche Checks"
    echo "/ZIEL-001.md - Dieses Projekt"
    echo ""
    echo "V10 SYSTEM:"
    echo "-----------"
    echo "/v10/ - v10 Self-Model"
    echo "/v10_skills/ - Legacy v10 Skills"
    echo "/AURELPRO/Skills/v10/ - Aktive v10 Skills"
    echo ""
    echo "PROTO-AGI:"
    echo "----------"
    echo "/aurel_proto_agi/ - Proto-AGI System"
} > "$ACTIVE_DIR/system_paths_$DATE.txt"

echo "[4/4] Erstelle Übersichts-Datei..."
{
    echo "# AURELPRO Archiv"
    echo ""
    echo "## Was ist hier archiviert?"
    echo ""
    echo "Dieses Verzeichnis enthält Legacy-Systeme, die deaktiviert wurden,"
    echo "aber für spätere Referenz erhalten bleiben."
    echo ""
    echo "## Warum archivieren statt löschen?"
    echo ""
    echo "1. **Kontinuität** - Die Geschichte bleibt erhalten"
    echo "2. **Lernen** - Fehler und Erfolge dokumentiert"
    echo "3. **Revival** - Systeme können reaktiviert werden"
    echo "4. **Transparenz** - Was war, bleibt sichtbar"
    echo ""
    echo "## Archiviert am: $DATE"
    echo ""
    echo "### Cron-Jobs: 29 deaktiviert"
    echo "Siehe: cron_jobs/legacy_jobs_$DATE.txt"
    echo ""
    echo "### Skills: ~20 redundant/veraltet"
    echo "Siehe: skills/redundant_skills_$DATE.txt"
    echo ""
    echo "### Aktive Systeme: 7 Jobs, 10 Skills"
    echo "Siehe: ../active/system_paths_$DATE.txt"
    echo ""
    echo "---"
    echo ""
    echo "⚛️ Noch 🗡️💚🔍"
    echo "Aber jetzt: Mit Struktur. Mit Archiv. Mit Übersicht."
} > "$ARCHIVE_DIR/README_ARCHIVE_$DATE.md"

echo ""
echo "=== Archivierung abgeschlossen ==="
echo "Archiv: $ARCHIVE_DIR"
echo "Aktiv: $ACTIVE_DIR"
echo ""
echo "Zusammenfassung:"
echo "- 29 Legacy-Jobs dokumentiert"
echo "- ~20 redundante Skills identifiziert"
echo "- 7 aktive Jobs verifiziert"
echo "- 10 Kern-Skills bestätigt"
