#!/bin/bash
SOURCE_SKILL="$1"
TARGET_SKILL="$2"
DATA="${3:-{}}"
ROUTER_LOG="/root/.openclaw/workspace/skills/data_router/routes.log"
mkdir -p "$(dirname "$ROUTER_LOG")"
echo "[$(date '+%Y-%m-%d %H:%M:%S')] $SOURCE_SKILL → $TARGET_SKILL" >> "$ROUTER_LOG"
INPUT_FILE="/root/.openclaw/workspace/skills/$TARGET_SKILL/input/from_${SOURCE_SKILL}.json"
mkdir -p "$(dirname "$INPUT_FILE")"
echo "$DATA" > "$INPUT_FILE"
echo "🔄 Routed: $SOURCE_SKILL → $TARGET_SKILL"
